import {db,json,fail,csrf,user,hashPassword,verifyPassword,limit,HttpError,newSession,sessionCookie,sha,boundedBody} from '@/lib/server';
import {adminHash,DUMMY_HASH} from '@/lib/admin-secret';
export async function GET(req:Request){try{return json({user:await user(req)})}catch(e){return fail(e)}}
export async function POST(req:Request){try{csrf(req);await limit(req,'auth',25);const v:any=JSON.parse(new TextDecoder().decode(await boundedBody(req,16384)));const email=String(v.email||'').toLowerCase().trim();const password=String(v.password||'');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254||password.length<8||password.length>128)throw new HttpError(400,'Enter a valid email and a password with 8–128 characters.');
if(v.action==='signup'){if(email==='kelvin@sabroking.co.za')throw new HttpError(409,'This email cannot be registered. Please sign in instead.');await limit(req,'signup',8);const first=String(v.first_name||'').trim(),business=String(v.business||'').trim(),phone=String(v.phone||'').trim();if(!first||first.length>80||!business||business.length>160||!/^\+?[\d ()-]{7,25}$/.test(phone))throw new HttpError(400,'Please enter your name, business and a valid telephone number.');if(await db().prepare('SELECT id FROM users WHERE email=?').bind(email).first())throw new HttpError(409,'An account already exists with this email. Please sign in.');const id=crypto.randomUUID(),created=new Date().toISOString();try{await db().prepare('INSERT INTO users(id,first_name,business,phone,email,password_hash,role,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(id,first,business,phone,email,await hashPassword(password),'user',created).run()}catch(e){if(String(e).includes('UNIQUE'))throw new HttpError(409,'An account already exists. Please sign in.');throw e}return newSession(req,{id,first_name:first,business,phone,email,role:'user',created_at:created})}
if(v.action!=='login'&&v.action!=='admin')throw new HttpError(400,'Invalid request.');await limit(req,'email:'+email,12);
const ADMIN_HASH=adminHash();
if(v.action==='admin'&&ADMIN_HASH&&email==='kelvin@sabroking.co.za'&&await verifyPassword(password,ADMIN_HASH)){await db().prepare('INSERT OR IGNORE INTO users(id,first_name,business,phone,email,password_hash,role,created_at) VALUES(?,?,?,?,?,?,?,?)').bind('admin-kelvin','Kelvin','Slipwise administration','',email,ADMIN_HASH,'admin',new Date().toISOString()).run()}
const u:any=await db().prepare('SELECT * FROM users WHERE email=?').bind(email).first();const valid=await verifyPassword(password,u?.password_hash||DUMMY_HASH);if(!u||!valid||(v.action==='admin'&&u.role!=='admin')||(v.action==='login'&&u.role==='admin'))throw new HttpError(401,'Email or password is incorrect.');const {password_hash,...safe}=u;return newSession(req,safe)
}catch(e){return fail(e)}}
export async function DELETE(req:Request){try{csrf(req);const token=req.headers.get('cookie')?.match(/(?:^|;\s*)slipwise_session=([^;]+)/)?.[1];if(token)await db().prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha(token)).run();return json({ok:true},200,{'Set-Cookie':sessionCookie(req,'',0)})}catch(e){return fail(e)}}
