import {env} from 'cloudflare:workers';
export function db(){if(!env.DB)throw new Error('Database unavailable');return env.DB}
export function bucket(){if(!env.BUCKET)throw new Error('File storage unavailable');return env.BUCKET}
export class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
export function json(data:unknown,status=200,extra:Record<string,string>={}){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...extra}})}
export function fail(e:unknown){if(e instanceof HttpError)return json({error:e.message},e.status);console.error('Request failed',e);return json({error:'We could not complete that request. Your changes have not been discarded. Please try again.'},503)}
export function csrf(req:Request){const origin=req.headers.get('origin');if(!origin||origin!==new URL(req.url).origin)throw new HttpError(403,'Please reload the app and try again.');if(req.headers.get('sec-fetch-site')==='cross-site')throw new HttpError(403,'Request not allowed')}
export async function sha(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(b=>b.toString(16).padStart(2,'0')).join('')}
function hex(a:Uint8Array){return Array.from(a).map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function hashPassword(password:string,salt=hex(crypto.getRandomValues(new Uint8Array(16)))){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},key,256);return `pbkdf2$100000$${salt}$${hex(new Uint8Array(bits))}`}
export async function verifyPassword(password:string,stored:string){const expected=await hashPassword(password,stored.split('$')[2]);let diff=expected.length^stored.length;for(let i=0;i<expected.length;i++)diff|=expected.charCodeAt(i)^(stored.charCodeAt(i)||0);return diff===0}
export async function limit(req:Request,label:string,max=20){const ip=req.headers.get('cf-connecting-ip')||'local';const key=await sha(label+':'+ip);const now=Date.now();const row=await db().prepare('INSERT INTO rate_limits (key,count,reset_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN reset_at<? THEN 1 ELSE count+1 END, reset_at=CASE WHEN reset_at<? THEN ? ELSE reset_at END RETURNING count').bind(key,now+900000,now,now,now+900000).first<{count:number}>();if((row?.count||0)>max)throw new HttpError(429,'Too many attempts. Please try again in 15 minutes.')}
export type User={id:string;first_name:string;business:string;phone:string;email:string;role:string;created_at:string};
export async function user(req:Request,role?:string){const token=req.headers.get('cookie')?.match(/(?:^|;\s*)slipwise_session=([^;]+)/)?.[1];if(!token)throw new HttpError(401,'Please sign in to continue.');const u=await db().prepare('SELECT u.id,u.first_name,u.business,u.phone,u.email,u.role,u.created_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires>?').bind(await sha(token),Date.now()).first<User>();if(!u)throw new HttpError(401,'Please sign in to continue.');if(role&&u.role!==role)throw new HttpError(403,'This account cannot access that information.');return u}
export function sessionCookie(req:Request,token:string,age=2592000){return `slipwise_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${age}${new URL(req.url).protocol==='https:'?'; Secure':''}`}
export async function newSession(req:Request,u:User){const token=hex(crypto.getRandomValues(new Uint8Array(32)));await db().prepare('INSERT INTO sessions(token_hash,user_id,expires) VALUES(?,?,?)').bind(await sha(token),u.id,Date.now()+2592000000).run();return json({user:u},200,{'Set-Cookie':sessionCookie(req,token)})}
export const categories=['General','Meals & coffee','Travel & fuel','Office supplies','Equipment','Software','Utilities','Stock','Other'];
export function fields(v:any){const supplier=String(v.supplier||'').trim();const date=String(v.date||'');const receipt=String(v.receipt_number||'').trim();const category=String(v.category||'General');const total=Number(v.total);const vat=v.vat===''||v.vat==null?null:Number(v.vat);if(!supplier||supplier.length>160||!/^\d{4}-\d{2}-\d{2}$/.test(date)||Number.isNaN(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date||!categories.includes(category)||v.total===''||!Number.isFinite(total)||total<0||total>99999999||receipt.length>100||vat!==null&&(!Number.isFinite(vat)||vat<0||vat>total))throw new HttpError(400,'Check the supplier, date, category and amounts. VAT cannot be more than the total.');return {supplier,date,receipt,category,total:Math.round(total*100),vat:vat===null?null:Math.round(vat*100)}}

export async function boundedBody(req:Request,max:number){if(Number(req.headers.get("content-length")||0)>max)throw new HttpError(413,"This upload is too large.");if(!req.body)throw new HttpError(400,"Request body is missing.");const reader=req.body.getReader();const chunks:Uint8Array[]=[];let size=0;try{while(true){const {value,done}=await reader.read();if(done)break;size+=value.byteLength;if(size>max){await reader.cancel();throw new HttpError(413,"This upload is too large.")}chunks.push(value)}}finally{reader.releaseLock()}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength}return bytes}
